version: "3.7"
services:
  app_dev:
    build:
      context: .
    image: schneidermatic/${APP_NAME}:${APP_RELEASE}
    container_name: "notifikator"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ID=nk01
      - APP_IMAGE=schneidermatic/${APP_NAME}:${APP_RELEASE}
      - APP_DESCRIPTION="Rule based event correlation service for Elasticsearch."
      - APP_RELEASE=${APP_RELEASE}
      - APP_IPADDRESS=0.0.0.0
      - APP_PORT=5005
      - APP_CONFIG_NAME=testing
      - APP_ADMIN_USER=admin
      - APP_ADMIN_PASSWORD=password
      - APP_THREAD_NUMB=1
      - APP_SLEEP_TIME=1
      - APP_FLASK_LOGGER=True
      - APP_ES_SETUP_ARTIFACTS=True
      - APP_KB_SETUP_ARTIFACTS=True
      - APP_ES_BOOTSTRAP_RETRY_INTERVAL=1
      - APP_ES_BOOTSTRAP_RETRY_MAX=300
      - APP_KB_BOOTSTRAP_RETRY_INTERVAL=1
      - APP_KB_BOOTSTRAP_RETRY_MAX=300
      - APP_LOG_DIR=./
      - APP_LOG_TYPE=stream
      - APP_LOG_LEVEL=DEBUG
      - APP_MAIN_LOG_NAME=app.log
      - APP_WWW_LOG_NAME=www.log
      - APP_LOG_MAX_BYTES=100_000_000
      - APP_LOG_COPIES=5
      - APP_ES_HOST=172.17.0.1
      - APP_ES_PORT=9200
      - APP_ES_USER=elastic
      - APP_ES_PASSWORD=changeme
      - APP_ES_USE_SSL=True
      - APP_ES_VERIFY_CERTS=False
      - APP_ES_CA_CERTS=/notifikator/ssl/elasticsearch.cer
      - APP_ES_TEMPLATE_FOLDER=/notifikator/app/templates
      - APP_ES_INDEX_01=incident
      - APP_ES_INDEX_02=imticket
      - APP_KB_HOST=172.17.0.1
      - APP_KB_PORT=5601
      - APP_KB_USER=elastic
      - APP_KB_PASSWORD=changeme
      - APP_KB_USE_SSL=True
      - APP_KB_VERIFY_CERTS=False
      - APP_KB_CA_CERTS=/notifikator/ssl/kibana.cer
      - APP_KB_TEMPLATE_FOLDER=/notifikator/app/templates/kibana
    restart: always
    ports: 
      - '5005:5005'
    volumes:
      - ./resources/ssl/:/notifikator/ssl
    networks:    
      - notifikator
      
  app_prod:
    build:
      context: .
    image: schneidermatic/${APP_NAME}:${APP_RELEASE}
    container_name: "notifikator"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ID=nk01
      - APP_IMAGE=schneidermatic/${APP_NAME}:${APP_RELEASE}
      - APP_DESCRIPTION="Rule based event correlation service for Elasticsearch."
      - APP_RELEASE=${APP_RELEASE}
      - APP_IPADDRESS=0.0.0.0
      - APP_PORT=8008
      - APP_CONFIG_NAME=production
      - APP_ADMIN_USER=admin
      - APP_ADMIN_PASSWORD=password
      - APP_THREAD_NUMB=1
      - APP_SLEEP_TIME=1
      - APP_FLASK_LOGGER=False
      - APP_ES_SETUP_ARTIFACTS=True
      - APP_KB_SETUP_ARTIFACTS=True
      - APP_ES_BOOTSTRAP_RETRY_INTERVAL=1
      - APP_ES_BOOTSTRAP_RETRY_MAX=300
      - APP_KB_BOOTSTRAP_RETRY_INTERVAL=1
      - APP_KB_BOOTSTRAP_RETRY_MAX=300
      - APP_LOG_DIR=./
      - APP_LOG_TYPE=stream
      - APP_LOG_LEVEL=INFO
      - APP_MAIN_LOG_NAME=app.log
      - APP_WWW_LOG_NAME=www.log
      - APP_LOG_MAX_BYTES=100_000_000
      - APP_LOG_COPIES=5
      - APP_ES_HOST=172.17.0.1
      - APP_ES_PORT=9200
      - APP_ES_USER=elastic
      - APP_ES_PASSWORD=changeme
      - APP_ES_USE_SSL=True
      - APP_ES_VERIFY_CERTS=False
      - APP_ES_CA_CERTS=/notifikator/ssl/elasticsearch.cer
      - APP_ES_TEMPLATE_FOLDER=/notifikator/app/templates
      - APP_ES_INDEX_01=incident
      - APP_ES_INDEX_02=imticket
      - APP_KB_HOST=172.17.0.1
      - APP_KB_PORT=5601
      - APP_KB_USER=elastic
      - APP_KB_PASSWORD=changeme
      - APP_KB_USE_SSL=True
      - APP_KB_VERIFY_CERTS=False
      - APP_KB_CA_CERTS=/notifikator/ssl/kibana.cer
      - APP_KB_TEMPLATE_FOLDER=/notifikator/app/templates/kibana
    restart: always
    ports: 
      - '8008:8008'
    volumes:
      - ./resources/ssl/:/notifikator/ssl
    networks:    
      - notifikator

networks:
  notifikator:
    driver: bridge

volumes:
  data01:
  certs:
